bus_system/config/routes.rb
BusSystem::Application.routes.draw do
  resources :stations
  resources :stops, only: [:index, :create, :destroy]
  resources :lines
  resources :buses


end

bus_system/app/models/bus.rb
class Bus < ActiveRecord::Base

  has_many :stops
  belongs_to :line
  has_many :stations, :through => :stops

end

bus_system/app/models/line.rb
class Line < ActiveRecord::Base

 has_many :stops
 has_many :buses
 has_many :stations, :through => :stops

end

bus_system/app/models/station.rb
class Station < ActiveRecord::Base

  has_many :stops
  has_many :lines, :through => :stops
  has_many :buses, :through => :stops

  validates :name, :uniqueness => true, :presence => :true

end

bus_system/app/models/stop.rb
class Stop < ActiveRecord::Base

  belongs_to :station
  belongs_to :line
  belongs_to :bus
end

bus_system/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

bus_system/app/controllers/buses_controller.rb
class BusesController < ApplicationController

  def index
    @buses = Bus.all
  end

  def new
    @bus = Bus.new
  end

  def show
    @bus = Bus.find(params[:id])
  end

  def create
    @bus = Bus.new(bus_params)
    if @bus.save
      flash[:notice] = "Bus created."
      redirect_to buses_path
    else
      render 'new'
    end
  end

  def edit
    @bus = Bus.find(params[:id])
  end

  def update
    @bus = Bus.find(params[:id])
    if @bus.update(bus_params)
      flash[:notice] = "Bus updated."
      redirect_to bus_path
    else
      render 'edit'
    end
  end

  def destroy
    @bus = Bus.find(params[:id])
    @bus.destroy
    redirect_to buses_path
  end

  private

  def bus_params
    params.require(:bus).permit(:name, :line_id)
  end

end

bus_system/app/controllers/lines_controller.rb
class LinesController < ApplicationController
  def index
    @lines = Line.all
  end

  def new
    @stop = Stop.new
    @line = Line.new
  end

  def show
    @line = Line.find(params[:id])
  end

  def create
    @line = Line.new(line_params)
    if @line.save
      flash[:notice] = "line created."
      redirect_to lines_path
    else
      render 'new'
    end
  end

  def edit
    @stop = Stop.new
    @line = Line.find(params[:id])
  end

  def update
    @line = Line.find(params[:id])
    if @line.update(line_params)
      flash[:notice] = "line updated."
      redirect_to line_path
    else
      render 'edit'
    end
  end

  def destroy
    @line = Line.find(params[:id])
    @line.destroy
    redirect_to lines_path
  end

  private

  def line_params
    params.require(:line).permit(:name)
  end

end

bus_system/app/controllers/stations_controller.rb
class StationsController < ApplicationController
  def index
    @stations = Station.all
  end

  def new
    @station = Station.new
    @stop = Stop.new
  end

  def show
    @station = Station.find(params[:id])
  end

  def create
    @station = Station.new(station_params)
    if @station.save
      flash[:notice] = "Station created."
      redirect_to stations_path
    else
      render 'new'
    end
  end

  def edit
    @station = Station.find(params[:id])
    @stop = Stop.new
  end

  def update
    @station = Station.find(params[:id])
    if @station.update(station_params)
      flash[:notice] = "Station updated."
      redirect_to station_path
    else
      render 'edit'
    end
  end

  def destroy
    @station = Station.find(params[:id])
    @station.destroy
    redirect_to stations_path
  end

  private

  def station_params
    params.require(:station).permit(:name)
  end

end

bus_system/app/controllers/stops_controller.rb
class StopsController < ApplicationController
  def index
    @stops = Stop.all
  end

  def new
    @stop = Stop.new
  end

  def show
    @stop = Stop.find(params[:id])
  end

  def create
    @stop = Stop.new(stop_params)
    if @stop.save
      flash[:notice] = "Stop created."
      redirect_to lines_path
    else
      render 'new'
    end
  end

  def edit
    @stop = Stop.find(params[:id])
  end

  def update
    @stop = Stop.find(params[:id])
    if @stop.update(stop_params)
      flash[:notice] = "Stop updated."
      redirect_to stop_path
    else
      render 'edit'
    end
  end

  def destroy
    @stop = Stop.find(params[:id])
    @stop.destroy
    redirect_to stops_path
  end

  private

  def stop_params
    params.require(:stop).permit(:station_id, :line_id, :time, :bus_id)
  end

end

bus_system/app/helpers/application_helper.rb
module ApplicationHelper
end

bus_system/app/views/buses/_form.html.erb
<%= render("layouts/errors", :object => @bus) %>

<%= form_for(@bus) do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="form-group">
    <%= f.label :line_id %>
    <% lines_array = Line.all.map { |line| [line.name, line.id]} %>
    <% lines_array.insert(0, []) %>
    <%= f.select(:line_id, options_for_select(lines_array)) %>
  </div>
  <%= f.submit(:class => 'btn btn-primary') %>
<% end %>

bus_system/app/views/buses/edit.html.erb
<h1>Edit <%= @bus.name %></h1>
<%= render 'form' %>

bus_system/app/views/buses/index.html.erb
<h1>Buses!</h1>

<ul>
  <% @buses.each do |bus| %>
    <li><a href='/buses/<%= bus.id %>'><%= bus.name %></a></li>
  <% end %>
</ul>

<%= link_to "New bus", new_bus_path, :class => "btn btn-default" %>

bus_system/app/views/buses/new.html.erb
<h1>Create new bus</h1>
<%= render 'form' %>

bus_system/app/views/buses/show.html.erb
<h1><%= @bus.name %></h1>

<% if @bus.line != nil %>
<h3>Line: <a href="/lines/<%= @bus.line.id %>"><%= @bus.line.name %></a></h3>
<% end %>

<%= link_to "Edit bus", edit_bus_path, :class => "btn btn-default" %>


<%= link_to "Delete bus", bus_path(@bus),
                        :confirm => "You sure?",
                        :method => "delete",
                        :class => "btn btn-danger" %>

<%= link_to "Back", buses_path, :class => "btn btn-default" %>

bus_system/app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

bus_system/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BusSystem</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <%= flash[:notice] %>
<%= yield %>
</div>
</body>
</html>

bus_system/app/views/lines/_form.html.erb
<%= render("layouts/errors", :object => @line) %>

<%= form_for(@line) do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <%= f.submit(:class => 'btn btn-primary') %>
<% end %>

<h3>Add a station to this line:</h3>
<%= form_for(@stop) do |f| %>
  <div class="form-group">
    <% f.label :line_id %>
    <%= f.hidden_field(:line_id, :value => "#{@line.id}") %>
  </div>
  <div class="form-group">
    <%= f.label :station_id %>
    <% stations_array = Station.all.map { |station| [station.name, station.id]} %>
    <% stations_array.insert(0, []) %>
    <%= f.select(:station_id, options_for_select(stations_array)) %>
  </div>

  <div class="form-group">
    <%= f.label :bus_id %>
    <% buses_array = @line.buses.map { |bus| [bus.name, bus.id]} %>
    <% buses_array.insert(0, []) %>
    <%= f.select(:bus_id, options_for_select(buses_array)) %>
  </div>
  <div class="form-group">
    <%= f.label :time %>
    <%= f.text_field :time %>
  </div>
  <%= f.submit(:class => 'btn btn-primary') %>
  <% end %>

bus_system/app/views/lines/edit.html.erb
<h1>Edit <%= @line.name %></h1>
<%= render 'form' %>

bus_system/app/views/lines/index.html.erb
<h1>Lines!</h1>

<ul>
  <% @lines.each do |line| %>
    <li><a href='/lines/<%= line.id %>'><%= line.name %></a></li>
  <% end %>
</ul>

<%= link_to "New line", new_line_path, :class => "btn btn-default" %>

bus_system/app/views/lines/new.html.erb
<h1>Create new line</h1>
<%= render 'form' %>

bus_system/app/views/lines/show.html.erb
<h1><%= @line.name %></h1>

<h3>Stations:</h3>
<ul>
  <% @line.stations.each do |station| %>
    <li><a href="/stations/<%= station.id %>"><%= station.name %></a></li>
  <% end %>
</ul>

<h3>Buses:</h3>
<ul>
  <% @line.buses.each do |bus| %>
    <li><a href="/buses/<%= bus.id %>"><%= bus.name %></a></li>
  <% end %>
</ul>

<h3>Stops:</h3>

<table class="table">
  <tr><th>ID</th>
      <th>Station</th>
      <th>Bus</th>
      <th>Time</th>
    </tr>
    <% @line.stops.order(:time).each do |stop| %>
      <tr>
        <td><%= stop.id %></td>
        <td><a href="/stations/<%= stop.station_id %>"><%= stop.station.name %></a></td>
        <td><a href="/buses/<%= stop.bus_id %>"><%= stop.bus.name %></a></td>
        <td><%= stop.time.strftime("%l:%M%P") %></td>
      </tr>
    <% end %>
</table>
<p><%= link_to "Edit line", edit_line_path, :class => "btn btn-default" %></p>


<p><%= link_to "Delete line", line_path(@line),
                        :confirm => "You sure?",
                        :method => "delete",
                        :class => "btn btn-danger" %></p>

<p><%= link_to "Back", lines_path, :class => "btn btn-default" %></p>

bus_system/app/views/stations/_form.html.erb
<%= render("layouts/errors", :object => @station) %>

<%= form_for(@station) do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <%= f.submit(:class => 'btn btn-primary') %>
<% end %>

<h3>Add a line to this station:</h3>
<%= form_for(@stop) do |f| %>
  <div class="form-group">
    <% f.label :station_id %>
    <%= f.hidden_field(:station_id, :value => "#{@station.id}") %>
  </div>
  <div class="form-group">
    <%= f.label :line_id %>
    <% lines_array = Line.all.map { |line| [line.name, line.id]} %>
    <% lines_array.insert(0, []) %>
    <%= f.select(:line_id, options_for_select(lines_array)) %>
  </div>
  <div class="form-group">
    <%= f.label :time %>
    <%= f.text_field :time %>
  </div>
  <%= f.submit(:class => 'btn btn-primary') %>
  <% end %>

bus_system/app/views/stations/show.html.erb
<h1><%= @station.name %></h1>

<h3>Lines:</h3>
<ul>
  <% @station.lines.each do |line| %>
    <li><a href="/lines/<%= line.id %>"><%= line.name %></a></li>
  <% end %>
</ul>


<h3>Stops:</h3>

  <% @station.stops.order(:time).each do |stop| %>
    <ul>
    <li><%= stop.time.strftime("%l:%M%P") %>
      <ul>
        <li>Bus: <%=stop.bus.name %></li>
        <li>Line: <%= stop.line.name %></li>
      </ul>
    </li>
  </ul>
  <% end %>


<p><%= link_to "Edit station", edit_station_path, :class => "btn btn-default" %></p>


<p><%= link_to "Delete station", station_path(@station),
                        :confirm => "You sure?",
                        :method => "delete",
                        :class => "btn btn-danger" %></p>

<p><%= link_to "Back", stations_path, :class => "btn btn-default" %></p>

bus_system/app/views/stops/_form.html.erb
<%= render("layouts/errors", :object => @stop) %>

<%= form_for(@stop) do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <%= f.submit(:class => 'btn btn-primary') %>
<% end %>

bus_system/app/views/stops/edit.html.erb
<h1>Edit <%= @stop.name %></h1>
<%= render 'form' %>

bus_system/app/views/stops/index.html.erb
<h1>Stops!</h1>

<table class="table">
  <tr><th>ID</th>
      <th>Station</th>
      <th>Line</th>
      <th>Bus</th>
      <th>Time</th>
    </tr>
    <% @stops.order(:time).each do |stop| %>
      <tr>
        <td><%= stop.id %></td>
        <td><a href="/stations/<%= stop.station_id %>"><%= stop.station.name %></a></td>
        <td><a href="/lines/<%= stop.line_id %>"><%= stop.line.name %></a></td>
        <td><a href="/buses/<%= stop.bus_id %>"><%= stop.bus.name %></a></td>
        <td><%= stop.time.strftime("%l:%M%P") %></td>
      </tr>
    <% end %>
</table>

<p><%= link_to "New line", new_line_path, :class => "btn btn-default" %></p>
<p><%= link_to "New station", new_station_path, :class => "btn btn-default" %></p>
<p><%= link_to "New bus", new_bus_path, :class => "btn btn-default" %></p>

bus_system/app/views/stops/new.html.erb
<h1>Create new stop</h1>
<%= render 'form' %>

bus_system/app/views/stops/show.html.erb
<h1><%= @stop.name %></h1>

<%= link_to "Edit stop", edit_stop_path, :class => "btn btn-default" %>


<%= link_to "Delete stop", stop_path(@stop),
                        :confirm => "You sure?",
                        :method => "delete",
                        :class => "btn btn-danger" %>

<%= link_to "Back", stops_path, :class => "btn btn-default" %>